const {Builder,By,Key,until}=require('../.qa/node_modules/selenium-webdriver');
const firefox=require('../.qa/node_modules/selenium-webdriver/firefox');
const fs=require('node:fs');
const assert=require('node:assert/strict');
(async()=>{
 const options=new firefox.Options().setBinary('/snap/firefox/current/usr/lib/firefox/firefox').addArguments('-headless').setPreference('network.proxy.type',0);
 const driver=await new Builder().usingServer('http://127.0.0.1:4444').forBrowser('firefox').setFirefoxOptions(options).build();
 try{
  await driver.manage().window().setRect({width:1440,height:1150});
  await driver.get('http://127.0.0.1:8765');
  await driver.wait(until.elementTextContains(driver.findElement(By.id('connection')),'已连接'),5000);
  await driver.sleep(400);
  fs.writeFileSync('docs/workbench.png',await driver.takeScreenshot(),'base64');
  console.log('initial screenshot saved');
  await driver.findElement(By.id('enable')).click();
  await driver.wait(until.elementTextContains(driver.findElement(By.id('enable')),'已启用'),2000);
  const read=()=>driver.executeAsyncScript("const done=arguments[0];fetch('/api/state').then(r=>r.json()).then(done)");
  const q0=(await read()).joints_deg[0];
  const plus=driver.findElement(By.css('[data-row="joint-0"] [data-sign="1"]'));
  await driver.actions().move({origin:plus}).press().pause(450).release().perform();
  await driver.sleep(250);
  const q1=(await read()).joints_deg[0];
  assert(q1>q0+.5,`mouse jog failed ${q0},${q1}`);
  await driver.sleep(200);assert(Math.abs((await read()).joints_deg[0]-q1)<.01);
  if(!await driver.findElement(By.id('keyboard')).isSelected())await driver.findElement(By.id('keyboard')).click();
  await driver.findElement(By.id('scene')).click();
  await driver.actions().sendKeys('6').keyDown(Key.ARROW_UP).pause(350).keyUp(Key.ARROW_UP).perform();
  await driver.sleep(200);
  assert((await read()).joints_deg[5]>6,'J6 keyboard jog failed');
  await driver.findElement(By.id('cart-tab')).click();
  await driver.wait(until.elementIsVisible(driver.findElement(By.id('cart-panel'))),1000);
  const p0=(await read()).pose[3];
  await driver.actions().move({origin:driver.findElement(By.css('[data-row="cart-3"] [data-sign="1"]'))}).press().pause(400).release().perform();
  await driver.sleep(200);
  assert(Math.abs((await read()).pose[3]-p0)>.1,'roll control failed');
  const grip=driver.findElement(By.id('grip-input'));
  await grip.clear();await grip.sendKeys('75');await driver.findElement(By.id('apply-grip')).click();
  await driver.sleep(400);
  assert((await read()).gripper_target_mm===75,'gripper target failed');
  await driver.actions().sendKeys(Key.SPACE).perform();await driver.sleep(200);
  assert(!(await read()).enabled,'space stop failed');
  await driver.findElement(By.id('save-pose')).click();await driver.findElement(By.id('pose-name')).sendKeys('测试位置');await driver.findElement(By.css('#save-form button')).click();await driver.sleep(200);
  assert((await driver.findElement(By.id('saved-list')).getText()).includes('测试位置'));
  await driver.findElement(By.id('help')).click();assert(await driver.findElement(By.id('dialog')).isDisplayed());await driver.findElement(By.id('close-dialog')).click();
  fs.writeFileSync('docs/cartesian.png',await driver.takeScreenshot(),'base64');
  await driver.manage().window().setRect({width:390,height:844});await driver.sleep(300);
  assert(await driver.executeScript('return document.documentElement.scrollWidth<=window.innerWidth+1'),'mobile horizontal overflow');
  fs.writeFileSync('docs/mobile.png',await driver.takeScreenshot(),'base64');
  console.log('PASS: mouse hold/release, J6 keyboard, rotation, gripper, stop, saved pose, help, responsive layout');
 }finally{await driver.quit();}
})().catch(e=>{console.error(e);process.exitCode=1});
